server:
  port: 8088
#setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.acc.cloud.ms: DEBUG
    
#Eureka Server

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/policy_fulfillment?useSSL=false
    username: root
    password: root
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8765/eureka/
      register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
              
    