server:
  port: 9411

#spring:
#  datasource:
#    schema: classpath:/mysql.sql
#    url: jdbc:mysql://localhost:3306/zipkin?autoReconnect=true&useSSL=false
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
#    initialize: true
#    continue-on-error: true
#  sleuth:
#    enabled: false
#
#zipkin:
#  storage:
#      type: mysql


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8765/eureka/
#      defaultZone: https://discovery-service.apps.apbg.apcf.io/eureka/
      register-with-eureka: true       
  
#setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.acc.cloud.ms: DEBUG
#    org.springframework.cloud.sleuth.instrument.messaging.MessagingSpanExtractor: ERROR
#    org.springframework.cloud.sleuth.util.ExceptionUtils: ERROR