zuul:
  prefix: /api
  routes:
    account-service:
#      path: http://localhost:8082
      path: /account-service/**
      service-id: account-service
      sensitive-headers:
      - Cookie
      - Set-Cookie
    submission-service:
      path: /submission-service
      service-id: submission-service
      sensitive-headers:
      - Cookie
      - Set-Cookie

server:
  port: 8087
#setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.acc.cloud.ms: DEBUG
    
#Eureka Server  
eureka:
  client:
    service-url:
      defaultZone: https://discovery-service.apps.apbg.apcf.io/eureka/      
      register-with-eureka: true
      
spring:
  profiles:
    active:
    - ${SPRING_PROFILES_ACTIVE:cloud}
  zipkin:
    base-url: https://distributed-tracing-server.apps.apbg.apcf.io/
    service:
      name: 
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
# User Info       
security:
  oauth2:
    resource:
      user-info-uri: http://auth-server.apps.apbg.apcf.io/uaa/user
      
---
zuul:
  prefix: /api
  routes:
    account-service:
#      path: http://localhost:8082
      path: /account-service/**
      service-id: account-service
      sensitive-headers:
      - Cookie
      - Set-Cookie
    submission-service:
      path: /submission-service
      service-id: submission-service
      sensitive-headers:
      - Cookie
      - Set-Cookie

server:
  port: 8087
#setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.acc.cloud.ms: DEBUG
    
#Eureka Server  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8765/eureka/
      register-with-eureka: true
      
spring:
  profiles:
    active:
    - ${SPRING_PROFILES_ACTIVE:local}
  zipkin:
    base-url: http://localhost:9411/
    service:
      name: 
  sleuth:
    enabled: true
    sampler:
      probability: 1.0

# User Info 
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:9999/uaa/user